#!/usr/bin/env bash
# Copyright 2017-2020 by SDRausty. All rights reserved, see LICENSE 🌎 🌍 🌏
# Hosting sdrausty.github.io/TermuxArch courtesy https://pages.github.com.
# https://sdrausty.github.io/TermuxArch/README has info about this project.
# https://sdrausty.github.io/TermuxArch/CONTRIBUTORS Thank you for your help.
# pacman install packages wrapper without system update
##############################################################################
# IFS=$'\n\t'
set -Eeuo pipefail
shopt -s nullglob globstar
unset LD_PRELOAD
VERSIONID=2.0.593
 
_TRPERR_() {  # run on script error
	local RV="$?"
	printf "\\e[?25h\\n\\e[1;48;5;138m %s\\e[0m\\n\\n" "TermuxArch WARNING:  Generated script signal ${RV:-unknown} near or at line number ${1:-unknown} by `${2:-command}`!"
	exit 201
}
 
_TRPET_() {  # run on exit
	local RV="$?" 
  	printf "" 
	 
	if [[ "$RV" = 0 ]]
	then
		printf "\\e[0;32m%s\\e[1;34m: \\e[1;32m%s\\e[0m\\n\\e[0m" "${0##*/} $@ 2.0.593" "DONE 🏁 "
		printf "\\e]2; %s: %s \007" "${0##*/} $@" "DONE 🏁 "
	else 
		printf "\\e[0;32m%s \\e[0m%s\\e[1;34m: \\e[1;32m%s\\e[0m\\n\\e[0m" "${0##*/} $@ 2.0.593" "[Exit Signal $RV]" "DONE  🏁 "
		printf "\033]2; %s: %s %s \007" "${0##*/} $@" "[Exit Signal $RV]" "DONE 🏁 "
	fi
	printf "\e[?25h\e[0m"
	set +Eeuo pipefail
	exit
}
 
_TRPSIG_() {  # run on signal
	printf "\\e[?25h\\e[1;7;38;5;0mTermuxArch WARNING:  Signal $? received!\\e[0m\\n"
 	exit 211
}
 
_TRPQ_() {  # run on quit
	printf "\\e[?25h\\e[1;7;38;5;0mTermuxArch WARNING:  Quit signal $? received!\\e[0m\\n"
 	exit 221
}
 
trap '_TRPERR_ $LINENO $BASH_COMMAND $?' ERR
trap _TRPET_ EXIT
trap _TRPSIG_ HUP INT TERM
trap _TRPQ_ QUIT
 
declare -g ARGS="$@"
umask 0022
_TRPET_() { # on exit
printf "\\e[?25h\\e[0m"
set +Eeuo pipefail
 	_PRINTTAIL_ "$ARGS"
}

_PRINTTAIL_() {
printf "\\e[0;32m%s %s %s\\e[1;34m: \\e[1;32m%s\\e[0m 🏁  \\n\\n\\e[0m" "TermuxArch ${0##*/}" "$ARGS" "$VERSIONID" "DONE 📱"
printf '\033]2;  🔑 TermuxArch %s:DONE 📱 \007' "${0##*/} $ARGS"
}

trap _TRPET_ EXIT
## pc begin ####################################################################
printf '\033]2;  🔑 TermuxArch %s 📲 \007' "${0##*/} $ARGS"
printf "\\n\\e[1;32m==> \\e[1;37m%s \\e[0;32m%s \\e[1;32m%s \\e[0;32m%s\\e[0m\\n\\n" "Running" "TermuxArch" "${0##*/} $ARGS" "$VERSIONID..."
[ "$UID" = "0" ] && SUDOCONF="" || SUDOCONF="sudo"
if [[ -z "${1:-}" ]]
then
printf "\\e[1;31m%s \\e[0m\\n" "Run command '${0##*/}' with at least one argument: exiting..."
elif [[ "$1" = "a" ]]
then
$SUDOCONF pacman --noconfirm --color=always -S base base-devel "${@:2}"
elif [[ "$1" = "ae" ]]
then
$SUDOCONF pacman --noconfirm --color=always -S base base-devel emacs "${@:2}" 
elif [[ "$1" = "a8" ]]
then
$SUDOCONF pacman --noconfirm --color=always -S base base-devel emacs jdk8-openjdk "${@:2}" 
else
$SUDOCONF pacman --noconfirm --color=always -S "$@"
fi
# pc EOF
